# Generated by Django 3.1.7 on 2021-12-18 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('country_code', models.IntegerField()),
                ('add', models.TextField()),
                ('locality', models.TextField()),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('res_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('avg_cost_for_two', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency', models.CharField(max_length=50)),
                ('has_table_booking', models.BooleanField()),
                ('has_online_booking', models.BooleanField()),
                ('agg_rating', models.IntegerField()),
                ('rating_color', models.CharField(max_length=200)),
                ('rating_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField()),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='restaurant.address')),
                ('cuisines', models.ManyToManyField(blank=True, null=True, related_name='cuisines', to='restaurant.Cuisines')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
